# Generated by Django 5.2.8 on 2025-12-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_toy', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('picture_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectedCats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cats', models.ManyToManyField(to='cats.cat')),
            ],
        ),
    ]
