# Generated by Django 5.2.8 on 2026-01-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectedCats',
        ),
    ]
